# Задание 3: Numpy + Pandas

Создайте в переменной Z Numpy вектор из нулей длины n.

In [2]:
import numpy as np

In [ ]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Посчитайте размер матрицы Z в байтах и выведите его на печать

In [ ]:
z.nbytes
zz = z.size * z.itemsize
zz

80

Считайте 2 числа:

- n - размер Numpy вектора
- x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.

Сохраните вектор в переменную Z.

In [ ]:
n = 10
x=4
v = np.full(n, 0)
v[x] = 1
print(v)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
z[3] = 1
z

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

Считайте 2 числа n, m.

Создайте вектор Z состоящий из чисел от n до m с шагом 1.

In [ ]:
n = 1
m = 11
v = np.arange(n, m, 2)
v

array([1, 3, 5, 7, 9])

In [ ]:
z = np.arange(3, 10)
z

array([3, 4, 5, 6, 7, 8, 9])

Дан вектор Z

"Разверните" его.

In [ ]:
z[::-1]

array([9, 8, 7, 6, 5, 4, 3])

Считайте 3 числа:

- n - количество элементов матрицы
- m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.

In [ ]:
z = np.arange(6).reshape((2, 3))
z

array([[0, 1, 2],
       [3, 4, 5]])

Дан вектор Z

Запишите в переменную NonZerros индексы ненулевых элементов.

Используйте функцию https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.nonzero.html

In [3]:
nz = np.nonzero([1,2,0,0,4,0]) #indices
print(nz)

(array([0, 1, 4]),)


In [3]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]]) #by dimension
x

array([[1, 0, 0],
 [0, 2, 0],
 [1, 1, 0]])

In [4]:
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [10]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]]) #the same but by indices
np.transpose(np.nonzero(x))

array([[0, 0],
 [1, 1],
 [2, 0],
 [2, 1]])

Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

Выведите на печать список чисел из этой матрицы, которые больше 3.

In [15]:
import numpy as np
matrixe = np.array([[[1, 2],
           [4, 5]],
          [[7, 8],
           [0, 0]]])
matrixe

array([[[1, 2],
        [4, 5]],

       [[7, 8],
        [0, 0]]])

In [13]:
matrixe[matrixe > 3]

array([4, 5, 7, 8])

Считайте число n

Создайте единичную матрицу размера n, сохраните результат в переменную Z.

In [18]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
np.random.seed(10)
w = np.random.random((3,3,3))
print(w)

[[[0.77132064 0.02075195 0.63364823]
  [0.74880388 0.49850701 0.22479665]
  [0.19806286 0.76053071 0.16911084]]

 [[0.08833981 0.68535982 0.95339335]
  [0.00394827 0.51219226 0.81262096]
  [0.61252607 0.72175532 0.29187607]]

 [[0.91777412 0.71457578 0.54254437]
  [0.14217005 0.37334076 0.67413362]
  [0.44183317 0.43401399 0.61776698]]]


In [27]:
w.ndim

3

In [28]:
w.shape

(3, 3, 3)

In [38]:
size_=w.size
size_

27

In [30]:
w.dtype

dtype('float64')

In [37]:
itemsize_=w.itemsize
itemsize_

8

In [32]:
w.nbytes

216

In [39]:
nbytes=itemsize_ * size_
nbytes

216

In [51]:
arr=np.random.randint(3, size=(8, 10))
arr

array([[0, 2, 0, 1, 0, 2, 2, 1, 0, 2],
 [1, 2, 2, 0, 2, 0, 2, 1, 2, 0],
 [0, 1, 2, 2, 1, 2, 2, 0, 2, 2],
 [1, 1, 0, 2, 2, 2, 0, 0, 1, 0],
 [2, 2, 0, 2, 2, 0, 0, 2, 2, 2],
 [1, 1, 1, 0, 1, 0, 0, 1, 1, 1],
 [2, 1, 2, 0, 2, 1, 0, 0, 0, 2],
 [1, 0, 0, 0, 2, 2, 1, 2, 0, 1]])

In [54]:
arr=np.random.rand(3, 4)
arr

array([[0.24687606, 0.69630427, 0.71227059, 0.14808693],
 [0.99774049, 0.26678101, 0.97661496, 0.41103701],
 [0.03305073, 0.34507125, 0.63435134, 0.68070545]])

Считайте 3 числа: n, m, l.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.

In [49]:
np.random.seed(42)
nml = np.random.random((2, 4, 3))
nml

array([[[0.37454012, 0.95071431, 0.73199394],
        [0.59865848, 0.15601864, 0.15599452],
        [0.05808361, 0.86617615, 0.60111501],
        [0.70807258, 0.02058449, 0.96990985]],

       [[0.83244264, 0.21233911, 0.18182497],
        [0.18340451, 0.30424224, 0.52475643],
        [0.43194502, 0.29122914, 0.61185289],
        [0.13949386, 0.29214465, 0.36636184]]])

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

- numpy.random.seed(42)
  
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

In [6]:
np.random.seed(42)
matrixe = np.random.rand(3, 4)
matrixe

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
 [0.15601864, 0.15599452, 0.05808361, 0.86617615],
 [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [7]:
matrixe_min = matrixe.min()
matrixe_max = matrixe.max()
print(matrixe_min, matrixe_max)

0.020584494295802447 0.9699098521619943


Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

- numpy.random.seed(42)
  
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение среднего для всей матрицы.

In [9]:
np.random.seed(42)
v = np.random.rand(2, 6)
v

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
 0.15599452],
 [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
 0.96990985]])

In [10]:
v.mean(axis = 0)

array([0.21631187, 0.90844523, 0.66655448, 0.65336553, 0.08830157,
 0.56295219])

In [11]:
v.mean(axis=1)

array([0.49465334, 0.53732362])

In [12]:
v.mean()

0.5159884754987122

In [ ]:
z = np.random.random((2, 3))
z

array([[0.06246188, 0.79471162, 0.99647445],
       [0.16882846, 0.53010937, 0.60352099]])

In [ ]:
z.mean(axis=0)

array([0.11564517, 0.66241049, 0.79999772])

In [ ]:
z.mean(axis=1)

array([0.61788265, 0.43415294])

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

- numpy.random.seed(42)
        
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Найдите среднее значение для каждого из столбцов.
Выведите на печать значение минимального и максимального среднего по столбцам (каждое с новой строки).

In [15]:
np.random.seed(42)
mm = np.random.rand(5, 8)
mm

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
 0.15599452, 0.05808361, 0.86617615],
 [0.60111501, 0.70807258, 0.02058449, 0.96990985, 0.83244264,
 0.21233911, 0.18182497, 0.18340451],
 [0.30424224, 0.52475643, 0.43194502, 0.29122914, 0.61185289,
 0.13949386, 0.29214465, 0.36636184],
 [0.45606998, 0.78517596, 0.19967378, 0.51423444, 0.59241457,
 0.04645041, 0.60754485, 0.17052412],
 [0.06505159, 0.94888554, 0.96563203, 0.80839735, 0.30461377,
 0.09767211, 0.68423303, 0.44015249]])

In [16]:
mm.mean(axis = 0)

array([0.36020379, 0.78352096, 0.46996585, 0.63648585, 0.4994685 ,
 0.13039 , 0.36476622, 0.40532382])

In [21]:
min_=mm.mean(axis = 0).min()
min_

0.13039000367858045

In [22]:
max_=mm.mean(axis=0).max()
max_

0.7835209628969093

Считайте число n.

Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до n.
Сохраните матрицу в переменную Z.

In [27]:
v = np.diag(np.arange(1, 5))
print(v)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [28]:
v = np.diag(np.arange(1, 5), k = 1)
print(v)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [29]:
v = np.diag(np.arange(1, 5), k = -1)
print(v)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Считайте 2 числа: n, m.
Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.
- 0 - "чёрное"
- 1 - "белое"

Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).
Матрицу сохраните в переменную Z.

In [32]:
sh = np.zeros((8,6), dtype=int)
sh[1::2,::2] = 1
sh[::2,1::2] = 1
print(sh)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z.

A и B могут содержать как int, так и float.

In [7]:
A = np.arange(1, 11, 1)
A

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [8]:
B = np.full(10, 2)
B

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
mnozh = A * B
mnozh

array([ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

In [11]:

import numpy as np
np.vdot(A, B)

110

Даны 2 матрицы: A и B.

Найдите произведение матриц и сохраните его в переменную Z.

Если найти произведение матриц невозможно, то запишите в Z строку:

- Упс! Что-то пошло не так...

In [13]:
A_m = np.arange(10).reshape((2, -1))
A_m

array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])

In [14]:
B_m = np.arange(4).reshape(2, -1)
B_m

array([[0, 1],
 [2, 3]])

In [17]:
try:
    A_m*B_m
except ValueError:
    print("Something is not right...")

Something is not right...


In [20]:
m1 = np.arange(3, 9).reshape((2, -1))
m1

array([[3, 4, 5],
 [6, 7, 8]])

In [24]:
m2=np.full(6, 2).reshape((3, -1))
m2

array([[2, 2],
 [2, 2],
 [2, 2]])

In [25]:
np.dot(m1, m2)

array([[24, 24],
 [42, 42]])

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого
отрицательные числа округляем всегда вниз до целого
0 остаётся 0

In [26]:
# create a numpy array
A = np.array([1.5, -2.7, 0, 3.2, -4.8, 2.1])

# round the elements of A to the nearest integer
Z = np.where(A > 0, np.ceil(A), np.floor(A)).astype(int)

# print the result
print(Z)

[ 2 -3  0  4 -5  3]


Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.

In [28]:
# create two numpy arrays
A = np.array([1, 2, 5, 8, 9])
B = np.array([2, 4, 6, 8, 10])

# find common elements between A and B
common = np.intersect1d(A, B)

# sort the common elements in ascending order and store them in Z
Z = np.sort(common)

# print the result
print(Z)

[2 8]


1-я входная строка - год (опционально месяц и день) в формате ISO начала отсчёта

2-я входная строка - год (опционально месяц и день) в формате ISO окончания отсчёта

Составьте список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).
Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

2005 - год

02 - месяц

25 - день

In [31]:
import numpy as np
from datetime import datetime, timedelta

# input start date as an ISO format string
start_date_str = '2023-03-28'

# input end date as an ISO format string
end_date_str = '2023-04-04'

# convert ISO format strings to datetime objects
start_date = datetime.fromisoformat(start_date_str)
end_date = datetime.fromisoformat(end_date_str)

# generate numpy array of dates with a step of 1 day
dates_array = np.array([(start_date + timedelta(days=i)).strftime('%Y-%m-%d') for i in range((end_date - start_date).days)])

# print the result
print(dates_array)

['2023-03-28' '2023-03-29' '2023-03-30' '2023-03-31' '2023-04-01'
 '2023-04-02' '2023-04-03']


In [36]:
import numpy as np
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index = labels)
df

animal 
 age 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 3 
 yes 
 
 
 c 
 snake 
 0.5 
 2 
 no 
 
 
 d 
 dog 
 NaN 
 3 
 yes 
 
 
 e 
 dog 
 5.0 
 2 
 no 
 
 
 f 
 cat 
 2.0 
 3 
 no 
 
 
 g 
 snake 
 4.5 
 1 
 no 
 
 
 h 
 cat 
 NaN 
 1 
 yes 
 
 
 i 
 dog 
 7.0 
 2 
 no 
 
 
 j 
 dog 
 3.0 
 1 
 no

In [37]:
df.describe()

age 
 visits 
 
 
 
 
 count 
 8.000000 
 10.000000 
 
 
 mean 
 3.437500 
 1.900000 
 
 
 std 
 2.007797 
 0.875595 
 
 
 min 
 0.500000 
 1.000000 
 
 
 25% 
 2.375000 
 1.000000 
 
 
 50% 
 3.000000 
 2.000000 
 
 
 75% 
 4.625000 
 2.750000 
 
 
 max 
 7.000000 
 3.000000

In [ ]:
type(df.describe())

pandas.core.frame.DataFrame

In [38]:
df.describe()['age']

count 8.000000
mean 3.437500
std 2.007797
min 0.500000
25% 2.375000
50% 3.000000
75% 4.625000
max 7.000000
Name: age, dtype: float64

In [39]:
df.describe()[['age', 'visits']]

age 
 visits 
 
 
 
 
 count 
 8.000000 
 10.000000 
 
 
 mean 
 3.437500 
 1.900000 
 
 
 std 
 2.007797 
 0.875595 
 
 
 min 
 0.500000 
 1.000000 
 
 
 25% 
 2.375000 
 1.000000 
 
 
 50% 
 3.000000 
 2.000000 
 
 
 75% 
 4.625000 
 2.750000 
 
 
 max 
 7.000000 
 3.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


Переменная df содержит DataFrame.

Переменная col содержит имя колонки

Переменная row содержит имя ИЛИ индекс строки

Выведите на печать содержимое ячейки

In [41]:
col = 'animal'
row='e'

a cat
b cat
c snake
d dog
e dog
f cat
g snake
h cat
i dog
j dog
Name: animal, dtype: object

In [42]:
df[col]

a cat
b cat
c snake
d dog
e dog
f cat
g snake
h cat
i dog
j dog
Name: animal, dtype: object

In [49]:
df['animal']

a cat
b cat
c snake
d dog
e dog
f cat
g snake
h cat
i dog
j dog
Name: animal, dtype: object

In [48]:
col = "animal"
row = "e"
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}, 
                    index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
df

animal 
 age 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 3 
 yes 
 
 
 c 
 snake 
 0.5 
 2 
 no 
 
 
 d 
 dog 
 NaN 
 3 
 yes 
 
 
 e 
 dog 
 5.0 
 2 
 no 
 
 
 f 
 cat 
 2.0 
 3 
 no 
 
 
 g 
 snake 
 4.5 
 1 
 no 
 
 
 h 
 cat 
 NaN 
 1 
 yes 
 
 
 i 
 dog 
 7.0 
 2 
 no 
 
 
 j 
 dog 
 3.0 
 1 
 no

In [57]:
df.loc['e']

animal dog
age 5.0
visits 2
priority no
Name: e, dtype: object

Переменная df содержит DataFrame.

Выведите на печать:

число непустых (не null) значений в колонке 'age'
75% квантиль для значений в колонке 'age'

In [ ]:
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']})
                 index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

In [52]:
df.age.isna().sum()

2

In [56]:
quantile_75 = df['age'].quantile(q=0.75)
quantile_75

4.625

Переменная df содержит DataFrame.

Выведите на печать 3 первых строки.

In [ ]:
df[:3]

animal 
 age 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 3 
 yes 
 
 
 c 
 snake 
 0.5 
 2 
 no

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [ ]:
df.iloc[:3, :2]

animal 
 age 
 
 
 
 
 a 
 cat 
 2.5 
 
 
 b 
 cat 
 3.0 
 
 
 c 
 snake 
 0.5

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5

Переменная df содержит DataFrame.

Выведите на печать строки с индексами 0, 2, 3.

Важно. Обратите внимание, что хотя у 1-ого Dataframe назначены произвольные строки в качестве индексов, к ним тем не менее можно обратиться и по их порядковым значениям!

In [ ]:
df.iloc[[0, 2, 3],]

animal 
 age 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 1 
 yes 
 
 
 c 
 snake 
 0.5 
 2 
 no 
 
 
 d 
 dog 
 NaN 
 3 
 yes

  animal  age  visits priority
a    cat  2.5       1      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes

In [59]:
df.loc[['b', 'e', 'f'],]

animal 
 age 
 visits 
 priority 
 
 
 
 
 b 
 cat 
 3.0 
 3 
 yes 
 
 
 e 
 dog 
 5.0 
 2 
 no 
 
 
 f 
 cat 
 2.0 
 3 
 no

Переменная df содержит DataFrame.

Выведите на печать только столбцы 'name' и 'age' (гарантируется, что они есть)

In [ ]:
df[['animal', 'age']]

animal 
 age 
 
 
 
 
 a 
 cat 
 2.5 
 
 
 b 
 cat 
 3.0 
 
 
 c 
 snake 
 0.5 
 
 
 d 
 dog 
 NaN 
 
 
 e 
 dog 
 5.0 
 
 
 f 
 cat 
 2.0 
 
 
 g 
 snake 
 4.5 
 
 
 h 
 cat 
 NaN 
 
 
 i 
 dog 
 7.0 
 
 
 j 
 dog 
 3.0

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

Переменная df содержит DataFrame.

Выведите на печать только столбцы 'name' и 'age' И строки 0, 2, 3 (гарантируется, что они есть)

In [68]:
df.iloc[[0, 2, 3], [0, 1]]

animal 
 age 
 
 
 
 
 a 
 cat 
 2.5 
 
 
 c 
 snake 
 0.5 
 
 
 d 
 dog 
 NaN

In [70]:
df.loc[['a', 'c', 'd'], ['animal', 'age']]

animal 
 age 
 
 
 
 
 a 
 cat 
 2.5 
 
 
 c 
 snake 
 0.5 
 
 
 d 
 dog 
 NaN

Переменная df содержит DataFrame.

Выведите на печать только данные, относящиеся к записям, возраст которых больше, указанного в переменной critical_age.

In [73]:
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'name': ['Murzik', 'Pushok', 'Kaa', 'Bobik', 'Strelka', 'Vaska', 'Kaa2', 'Murka', 'Graf', 'Muhtar'],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}, 
                  index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
                 
print(df)
critical_age = 3

  animal  age     name  visits priority
a    cat  2.5   Murzik       1      yes
b    cat  3.0   Pushok       3      yes
c  snake  0.5      Kaa       2       no
d    dog  NaN    Bobik       3      yes
e    dog  5.0  Strelka       2       no
f    cat  2.0    Vaska       3       no
g  snake  4.5     Kaa2       1       no
h    cat  NaN    Murka       1      yes
i    dog  7.0     Graf       2       no
j    dog  3.0   Muhtar       1       no


In [ ]:
df[df['age'] > 3]

animal 
 age 
 visits 
 priority 
 
 
 
 
 e 
 dog 
 5.0 
 2 
 no 
 
 
 g 
 snake 
 4.5 
 1 
 no 
 
 
 i 
 dog 
 7.0 
 2 
 no

  animal  age  visits priority
e    dog  5.0       2       no
g  snake  4.5       1       no
i    dog  7.0       2       no

Переменная df содержит DataFrame.

Выведите на печать только данные, в которых не заполнен возраст (в графе 'age' стоит null)

In [85]:
null_age_rows = df[df['age'].isnull()]
print(null_age_rows)

  animal  age   name  visits priority
d    dog  NaN  Bobik       3      yes
h    cat  NaN  Murka       1      yes


Переменная df содержит DataFrame.

Переменная filter_names содержит список имён столбцов по которым происходит фильтрация

Переменная filter_values содержит список из 2 значений по которым происходит фильтрация. 1 значение проверяется на равенство. 2 значение должно быть меньше указанного в фильтре.

Выведите только те строки датафрейма, которые удовлетворяют условиям обоих фильтров.

В 1 примере мы выводим данные обо всех животных (имя столбца = 'animal'), являющихся кошками (значение = 'cat'), возраст (имя столбца = 'age') которых меньше 3 (значение = 3).

In [93]:
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'name': ['Murzik', 'Pushok', 'Kaa', 'Bobik', 'Strelka', 'Vaska', 'Kaa2', 'Murka', 'Graf', 'Muhtar'],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']},
                    index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

print(df)
filter_names = ["animal", "age"]
filter_values = ["cat", 3]

  animal  age     name  visits priority
a    cat  2.5   Murzik       1      yes
b    cat  3.0   Pushok       3      yes
c  snake  0.5      Kaa       2       no
d    dog  NaN    Bobik       3      yes
e    dog  5.0  Strelka       2       no
f    cat  2.0    Vaska       3       no
g  snake  4.5     Kaa2       1       no
h    cat  NaN    Murka       1      yes
i    dog  7.0     Graf       2       no
j    dog  3.0   Muhtar       1       no


In [ ]:
df[(df['age'] < 3) & (df['animal'] == 'cat')]

animal 
 age 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 1 
 yes 
 
 
 f 
 cat 
 2.0 
 3 
 no

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [ ]:
df[(df['age'] < 3) | (df['animal'] == 'cat')]

animal 
 age 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 3 
 yes 
 
 
 c 
 snake 
 0.5 
 2 
 no 
 
 
 f 
 cat 
 2.0 
 3 
 no 
 
 
 h 
 cat 
 NaN 
 1 
 yes

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
f    cat  2.0       3       no
h    cat  NaN       1      yes

Переменная df содержит DataFrame.

Переменная age_between содержит 2 числа

Выведите только те строки датафрейма, возраст в которых находится в интервале между числами age_between (включая границы).

In [90]:
age_between = [2, 4]
df[(df['age'] > 2) & (df['age'] < 4)]

animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 Murzik 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 Pushok 
 3 
 yes 
 
 
 j 
 dog 
 3.0 
 Muhtar 
 1 
 no

Переменная df содержит DataFrame.

Переменная index содержит строку ИЛИ число (индекс)

Увеличьте значение возраста в строке индексом равным index на 1.

Выведите df на печать.

In [94]:
index = 'f'
df.loc['f', 'age'] += 1
print(df)

  animal  age     name  visits priority
a    cat  2.5   Murzik       1      yes
b    cat  3.0   Pushok       3      yes
c  snake  0.5      Kaa       2       no
d    dog  NaN    Bobik       3      yes
e    dog  5.0  Strelka       2       no
f    cat  3.0    Vaska       3       no
g  snake  4.5     Kaa2       1       no
h    cat  NaN    Murka       1      yes
i    dog  7.0     Graf       2       no
j    dog  3.0   Muhtar       1       no


Переменная df содержит DataFrame.

Увеличьте значение возраста во всех строках на 1.

Выведите df на печать.

In [95]:
df

animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 Murzik 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 Pushok 
 3 
 yes 
 
 
 c 
 snake 
 0.5 
 Kaa 
 2 
 no 
 
 
 d 
 dog 
 NaN 
 Bobik 
 3 
 yes 
 
 
 e 
 dog 
 5.0 
 Strelka 
 2 
 no 
 
 
 f 
 cat 
 3.0 
 Vaska 
 3 
 no 
 
 
 g 
 snake 
 4.5 
 Kaa2 
 1 
 no 
 
 
 h 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 i 
 dog 
 7.0 
 Graf 
 2 
 no 
 
 
 j 
 dog 
 3.0 
 Muhtar 
 1 
 no

In [97]:
df['age'] = df['age'] + 1
df

index 
 animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 0 
 a 
 cat 
 3.5 
 Murzik 
 1 
 yes 
 
 
 1 
 b 
 cat 
 4.0 
 Pushok 
 3 
 yes 
 
 
 2 
 c 
 snake 
 1.5 
 Kaa 
 2 
 no 
 
 
 3 
 d 
 dog 
 NaN 
 Bobik 
 3 
 yes 
 
 
 4 
 e 
 dog 
 6.0 
 Strelka 
 2 
 no 
 
 
 5 
 f 
 cat 
 4.0 
 Vaska 
 3 
 no 
 
 
 6 
 g 
 snake 
 5.5 
 Kaa2 
 1 
 no 
 
 
 7 
 h 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 8 
 i 
 dog 
 8.0 
 Graf 
 2 
 no 
 
 
 9 
 j 
 dog 
 4.0 
 Muhtar 
 1 
 no

In [98]:
df.reset_index(inplace = True)
df

level_0 
 index 
 animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 0 
 0 
 a 
 cat 
 3.5 
 Murzik 
 1 
 yes 
 
 
 1 
 1 
 b 
 cat 
 4.0 
 Pushok 
 3 
 yes 
 
 
 2 
 2 
 c 
 snake 
 1.5 
 Kaa 
 2 
 no 
 
 
 3 
 3 
 d 
 dog 
 NaN 
 Bobik 
 3 
 yes 
 
 
 4 
 4 
 e 
 dog 
 6.0 
 Strelka 
 2 
 no 
 
 
 5 
 5 
 f 
 cat 
 4.0 
 Vaska 
 3 
 no 
 
 
 6 
 6 
 g 
 snake 
 5.5 
 Kaa2 
 1 
 no 
 
 
 7 
 7 
 h 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 8 
 8 
 i 
 dog 
 8.0 
 Graf 
 2 
 no 
 
 
 9 
 9 
 j 
 dog 
 4.0 
 Muhtar 
 1 
 no

In [99]:
df.set_index('index', inplace=True, drop=True)
df

level_0 
 animal 
 age 
 name 
 visits 
 priority 
 
 
 index 
 
 
 
 
 
 
 
 
 
 
 a 
 0 
 cat 
 3.5 
 Murzik 
 1 
 yes 
 
 
 b 
 1 
 cat 
 4.0 
 Pushok 
 3 
 yes 
 
 
 c 
 2 
 snake 
 1.5 
 Kaa 
 2 
 no 
 
 
 d 
 3 
 dog 
 NaN 
 Bobik 
 3 
 yes 
 
 
 e 
 4 
 dog 
 6.0 
 Strelka 
 2 
 no 
 
 
 f 
 5 
 cat 
 4.0 
 Vaska 
 3 
 no 
 
 
 g 
 6 
 snake 
 5.5 
 Kaa2 
 1 
 no 
 
 
 h 
 7 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 i 
 8 
 dog 
 8.0 
 Graf 
 2 
 no 
 
 
 j 
 9 
 dog 
 4.0 
 Muhtar 
 1 
 no

Переменная df содержит DataFrame.

Выведите на печать сумму всех возрастов в df.

In [100]:
sum_= df['age'].sum()
sum_

36.5

Переменная df содержит DataFrame.

Выведите на печать для каждого столбца, содержащего числа его имя и сумму через двоеточие.

In [101]:
for col in df.columns:
    if df[col].dtype in [np.int64, np.float64]:
        print(col + ':' + str(df[col].sum()))

level_0:45
age:36.5
visits:19


Переменная df содержит DataFrame.

Переменная group_by содержит имя колонки по которой производится группировка.

Найдите средние значение возраста по всем записям, сгруппированным по значению в колонке group_by и выведите на печать.

In [106]:
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'name': ['Murzik', 'Pushok', 'Kaa', 'Bobik', 'Strelka', 'Vaska', 'Kaa2', 'Murka', 'Graf', 'Muhtar'],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}, index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
group_by = "animal"

In [ ]:
df.groupby(['animal'])['age'].mean().reset_index()

animal 
 age 
 
 
 
 
 0 
 cat 
 2.5 
 
 
 1 
 dog 
 5.0 
 
 
 2 
 snake 
 2.5

  animal  age
0    cat  2.5
1    dog  5.0
2  snake  2.5

In [107]:
res = df.groupby(['animal', 'priority']).agg({'age': ['sum', 'mean', 'std'],
                           'visits':'sum'})
res

age 
 visits 
 
 
 
 
 sum 
 mean 
 std 
 sum 
 
 
 animal 
 priority 
 
 
 
 
 
 
 
 
 cat 
 no 
 2.0 
 2.00 
 NaN 
 3 
 
 
 yes 
 5.5 
 2.75 
 0.353553 
 5 
 
 
 dog 
 no 
 15.0 
 5.00 
 2.000000 
 5 
 
 
 yes 
 0.0 
 NaN 
 NaN 
 3 
 
 
 snake 
 no 
 5.0 
 2.50 
 2.828427 
 3

Переменная df содержит DataFrame.

new_index - индекс для строки, которую надо добавить
new_data - значения для строки, которую надо добавить
del_index - индекс строки, которую надо удалить
Добавьте новую строку (с индексом new_index и значениями new_data) и удалите одну из старых (del_index)

Выведите df на печать.

In [ ]:
res['age']['sum']

animal  priority
cat     no           2.0
        yes          5.5
dog     no          15.0
        yes          0.0
snake   no           5.0
Name: sum, dtype: float64

In [ ]:
res.reset_index()

animal 
 priority 
 age 
 visits 
 
 
 
 
 
 sum 
 mean 
 std 
 
 
 
 
 0 
 cat 
 no 
 2.0 
 2.00 
 NaN 
 
 
 1 
 cat 
 yes 
 5.5 
 2.75 
 1.154701 
 
 
 2 
 dog 
 no 
 15.0 
 5.00 
 0.577350 
 
 
 3 
 dog 
 yes 
 0.0 
 NaN 
 NaN 
 
 
 4 
 snake 
 no 
 5.0 
 2.50 
 0.707107

  animal priority   age          visits
                    sum  mean       std
0    cat       no   2.0  2.00       NaN
1    cat      yes   5.5  2.75  1.154701
2    dog       no  15.0  5.00  0.577350
3    dog      yes   0.0   NaN       NaN
4  snake       no   5.0  2.50  0.707107

Переменная df содержит DataFrame.

new_index - индекс для строки, которую надо добавить new_data - значения для строки, которую надо добавить del_index - индекс строки, которую надо удалить Добавьте новую строку (с индексом new_index и значениями new_data) и удалите одну из старых (del_index)

Выведите df на печать.

In [110]:
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'name': ['Murzik', 'Pushok', 'Kaa', 'Bobik', 'Strelka', 'Vaska', 'Kaa2', 'Murka', 'Graf', 'Muhtar'],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}, 
                    index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
new_index = "k"
new_data = [5.5, "dog", "Belka", "no", 2]
del_index = "f"

In [111]:
# Add new row
df.loc['k'] = new_data

# Remove old row
df = df.drop(del_index)
df

animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 Murzik 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 Pushok 
 3 
 yes 
 
 
 c 
 snake 
 0.5 
 Kaa 
 2 
 no 
 
 
 d 
 dog 
 NaN 
 Bobik 
 3 
 yes 
 
 
 e 
 dog 
 5.0 
 Strelka 
 2 
 no 
 
 
 g 
 snake 
 4.5 
 Kaa2 
 1 
 no 
 
 
 h 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 i 
 dog 
 7.0 
 Graf 
 2 
 no 
 
 
 j 
 dog 
 3.0 
 Muhtar 
 1 
 no 
 
 
 k 
 5.5 
 dog 
 Belka 
 no 
 2

Переменная df содержит DataFrame.

Переменная sort_by содержит список из 2 строк - имён столбцов по которым необходимо провести сортировку.

Отсортируйте сперва по уменьшению 1 поля из списка sort_by, а при равенстве значений по увеличению 2.

Выведите df на печать.

In [114]:
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'name': ['Murzik', 'Pushok', 'Kaa', 'Bobik', 'Strelka', 'Vaska', 'Kaa2', 'Murka', 'Graf', 'Muhtar'],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']},
                  index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
sort_by = ["age", "visits"]

In [115]:
df = df.sort_values(by=sort_by, ascending=[False, True])
df

animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 i 
 dog 
 7.0 
 Graf 
 2 
 no 
 
 
 e 
 dog 
 5.0 
 Strelka 
 2 
 no 
 
 
 g 
 snake 
 4.5 
 Kaa2 
 1 
 no 
 
 
 j 
 dog 
 3.0 
 Muhtar 
 1 
 no 
 
 
 b 
 cat 
 3.0 
 Pushok 
 3 
 yes 
 
 
 a 
 cat 
 2.5 
 Murzik 
 1 
 yes 
 
 
 f 
 cat 
 2.0 
 Vaska 
 3 
 no 
 
 
 c 
 snake 
 0.5 
 Kaa 
 2 
 no 
 
 
 h 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 d 
 dog 
 NaN 
 Bobik 
 3 
 yes

Переменная df содержит DataFrame.

Переменная column содержит имя колонки, содержащей строковые значения "yes", "no", либо числовые 1 или 0.

Замените в column:

"yes" и 1 на True
"no" и 0 на False
Выведите df на печать

In [116]:
df

animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 i 
 dog 
 7.0 
 Graf 
 2 
 no 
 
 
 e 
 dog 
 5.0 
 Strelka 
 2 
 no 
 
 
 g 
 snake 
 4.5 
 Kaa2 
 1 
 no 
 
 
 j 
 dog 
 3.0 
 Muhtar 
 1 
 no 
 
 
 b 
 cat 
 3.0 
 Pushok 
 3 
 yes 
 
 
 a 
 cat 
 2.5 
 Murzik 
 1 
 yes 
 
 
 f 
 cat 
 2.0 
 Vaska 
 3 
 no 
 
 
 c 
 snake 
 0.5 
 Kaa 
 2 
 no 
 
 
 h 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 d 
 dog 
 NaN 
 Bobik 
 3 
 yes

In [117]:
df['priority'] = df['priority'].map(lambda v: 1 if v == 'yes' else 0)
df

animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 i 
 dog 
 7.0 
 Graf 
 2 
 0 
 
 
 e 
 dog 
 5.0 
 Strelka 
 2 
 0 
 
 
 g 
 snake 
 4.5 
 Kaa2 
 1 
 0 
 
 
 j 
 dog 
 3.0 
 Muhtar 
 1 
 0 
 
 
 b 
 cat 
 3.0 
 Pushok 
 3 
 1 
 
 
 a 
 cat 
 2.5 
 Murzik 
 1 
 1 
 
 
 f 
 cat 
 2.0 
 Vaska 
 3 
 0 
 
 
 c 
 snake 
 0.5 
 Kaa 
 2 
 0 
 
 
 h 
 cat 
 NaN 
 Murka 
 1 
 1 
 
 
 d 
 dog 
 NaN 
 Bobik 
 3 
 1

Переменная df содержит DataFrame.

Переменная column содержит имя колонки, значения в которой надо модифицировать.

Переменные old_value и new_value содержат старое и новое значения, соответственно.

Замените все старые значения на новые в соответсвующей колонке.

Выведите df на печать

In [119]:
df = pd.DataFrame({'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'name': ['Murzik', 'Pushok', 'Kaa', 'Bobik', 'Strelka', 'Vaska', 'Kaa2', 'Murka', 'Graf', 'Muhtar'],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}, 
                  index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
column = 'animal'
old_value = 'snake'
new_value = 'python'

In [123]:
df['animal'] = df['animal'].replace(old_value, new_value)
df

animal 
 age 
 name 
 visits 
 priority 
 
 
 
 
 a 
 cat 
 2.5 
 Murzik 
 1 
 yes 
 
 
 b 
 cat 
 3.0 
 Pushok 
 3 
 yes 
 
 
 c 
 python 
 0.5 
 Kaa 
 2 
 no 
 
 
 d 
 dog 
 NaN 
 Bobik 
 3 
 yes 
 
 
 e 
 dog 
 5.0 
 Strelka 
 2 
 no 
 
 
 f 
 cat 
 2.0 
 Vaska 
 3 
 no 
 
 
 g 
 python 
 4.5 
 Kaa2 
 1 
 no 
 
 
 h 
 cat 
 NaN 
 Murka 
 1 
 yes 
 
 
 i 
 dog 
 7.0 
 Graf 
 2 
 no 
 
 
 j 
 dog 
 3.0 
 Muhtar 
 1 
 no